[model]
"backbone" = "resnet18"
"lr_backbone" = 1e-5
"no_encoder" = False
"state_dim" = 14
"action_dim" = 14
"num_queries" = 100
"latent_dim" = 32
"hidden_dim" = 256
"nheads" = 8
"dim_feedforward" = 2048
"enc_layers" = 4
"dec_layers" = 7
"dropout" = 0.1
"pre_norm" = False

[train]
"kl_weight" = 10
"lr" = 1e-4
"weight_decay" = 1e-4
"batch" = 128
"epoch" = 2000
"seed" = 42
"device" = 0

[io]
"camera_names" = []
