[model]
"backbone" = "resnet18"
"lr_backbone" = 1e-5
"no_encoder" = 0
"state_dim" = 7
"action_dim" = 7
"action_horizon" = 10
"latent_dim" = 32
"hidden_dim" = 256
"nheads" = 8
"dim_feedforward" = 1024
"enc_layers" = 4
"dec_layers" = 7
"dropout" = 0.1
"pre_norm" = 1

[train]
"seed" = 52
"batch" = 10
"epoch" = 1000
"kl_weight" = 10
"lr" = 7e-4
"weight_decay" = 1e-4
"save_epochs" = 100

[dataset]
"cameras" = ['head_camera']
"full_episode" = 0
"norm_mode" = "mean_std"